# Gene-environment interaction

Han SS, Chatterjee N (2018) Review of Statistical Methods for Gene-Environment Interaction Analysis. Current Epidemiology Reports 5: 39-45

## Single step methods

### Case-control

### Case-only

### Empirical Bayes and Bayesian Model Averaging

## Multi stage methods

## Joint tests

## Set-based interaction tests

Lin X, Lee S, Christiani DC, Lin X (2013) Test for interactions between a genetic marker set and environment in generalized linear models. Biostatistics 14: 667-81

Lin X, Lee S, Wu MC, Wang C, Chen H, Li Z, Lin X (2016) Test for rare variants by environment interactions in sequencing association studies. Biometrics 72: 156-64

Windle M. (2016) Statistical approaches to gene x environment interactions for complex phenotypes

## Combining multiple environments

## Variance heterogeneity

https://bmcgenet.biomedcentral.com/articles/10.1186/1471-2156-11-92

FTO genotype is associated with phenotypic variability of body mass index

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3659368/

https://academic.oup.com/jxb/article/68/20/5431/4093043

### Levene's test

### Generalized Levene's scale tests

Soave D, Sun L (2017) A generalized Levene's scale test for variance heterogeneity in the presence of sample correlation and group uncertainty. Biometrics 73: 960-971

### Two-step screening on residual variance heterogeneity

## Conditional quantile regression 

## RELIEF and other machine learning tools

### Multidimensionality reduction

## Meta-analytic GxE approaches

## Other challanges

### Controlling for covariate interactions

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3859520/pdf/nihms532193.pdf

## Candidate gene-by-environment interaction studies

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3859520/pdf/nihms532193.pdf

## Higher order interactions

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3859520/pdf/nihms532193.pdf

